name: A job to build doxgen document and deploy it on github-pages
on:
  push:
    branches:
      - main
      - master
      - 'doxygen*'
  workflow_dispatch:

jobs:
  doxygen-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: download modern theme
        run: |
          curl -OL https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css
      - uses: mattnotmitt/doxygen-action@v1.9.5
      - name: copy image
        run: cp -r docs html
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "html"
